##
# Copyrights:  2025 Codoworks.com
# Author:      Dexter Codo
# Website:     https://dexterexplains.com 
# Contact:     hello@dexterexplains.com
# Project:     Kubernetes Installer
##

# PLAYBOOK CONFIG ----------------------------------------------------------------------------
- hosts: initializing_master_node
  become: true
  gather_facts: true

  # VAR PROMPTS ------------------------------------------------------------------------------

  # vars_prompt:
  #  - name: "var_name"
  #    prompt: "User prompt? change me..."
  #    private: false # should this be visible or hidden like a password
     
  # TASKS ------------------------------------------------------------------------------------
  tasks: 
  # PRE-FLIGHT CHECKS ------------------------------------------------------------------------
  - name: Pre-flight check, fail if OS is not Ubuntu.
    when: ansible_distribution != "Ubuntu"
    fail:
      msg: "This script is designed for Ubuntu"
      
  # PRE-CONFIG -------------------------------------------------------------------------------
  - name: Whoami on the node?
    become: false
    shell: whoami
    register: node_username_raw

  - name: Set whoami on the node as a fact.
    set_fact:
      node_username: "{{ node_username_raw.stdout_lines[0] }}"

  # BEGIN ------------------------------------------------------------------------------------
  - name: Download Metrics Server Components.
    get_url:
      url: "https://github.com/kubernetes-sigs/metrics-server/releases/download/{{ metrics_server_version }}/components.yaml"
      dest: "/home/{{ node_username }}/metrics_server_components.yaml"

  - name: Configure Metrics Server to work without TLS verification.
    blockinfile:
      path: "/home/{{ node_username }}/metrics_server_components.yaml"
      insertafter: "- args:"
      block: "        - --kubelet-insecure-tls"

  - name: Install Metrics Server.
    become: true
    become_user: "{{ node_username }}"
    shell: "kubectl apply -f /home/{{ node_username }}/metrics_server_components.yaml >> metrics_server_setup.log"
    args:
      chdir: "/home/{{ node_username }}"
      creates: metrics_server_setup.log
  
  # TODO:- add Kubernetes CA authority to kube-system as a config map
  #        and mount that onto the pod, that way you don't need to 
  #        skip the TLS verification.

  # CLEAN UP ---------------------------------------------------------------------------------