##
# Copyrights:  2025 Codoworks.com
# Author:      Dexter Codo
# Website:     https://dexterexplains.com 
# Contact:     hello@dexterexplains.com
# Project:     Kubernetes Installer
##

# PLAYBOOK CONFIG ----------------------------------------------------------------------------
- hosts: initializing_master_node
  become: true
  gather_facts: true

  # VAR PROMPTS ------------------------------------------------------------------------------

  # vars_prompt:
  #  - name: "var_name"
  #    prompt: "User prompt? change me..."
  #    private: false # should this be visible or hidden like a password
     
  # TASKS ------------------------------------------------------------------------------------
  tasks: 
  # PRE-FLIGHT CHECKS ------------------------------------------------------------------------
  - name: Pre-flight check, fail if OS is not Ubuntu.
    when: ansible_distribution != "Ubuntu"
    fail:
      msg: "This script is designed for Ubuntu"

  # PRE-CONFIG -------------------------------------------------------------------------------
  - name: Whoami on the node?
    become: false
    shell: whoami
    register: node_username_raw

  - name: Set whoami on the node as a fact.
    set_fact:
      node_username: "{{ node_username_raw.stdout_lines[0] }}"

  # BEGIN ------------------------------------------------------------------------------------
  - name: Install Ingress Nginx Controller.
    become: true
    become_user: "{{ node_username }}"
    shell: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/{{ ingress_nginx_version }}/deploy/static/provider/baremetal/deploy.yaml >> ingress_nginx_setup.log"
    args:
      chdir: "/home/{{ node_username }}"
      creates: ingress_nginx_setup.log
      
  # CLEAN UP ---------------------------------------------------------------------------------