##
# Copyrights:  2025 Codoworks.com
# Author:      Dexter Codo
# Website:     https://dexterexplains.com 
# Contact:     hello@dexterexplains.com
# Project:     Kubernetes Installer
##

# PLAYBOOK CONFIG ----------------------------------------------------------------------------
- hosts: k8s_masters, worker_nodes
  become: true
  gather_facts: true
  
  # VAR PROMPTS ------------------------------------------------------------------------------

  # vars_prompt:
  #  - name: "var_name"
  #    prompt: "User prompt? change me..."
  #    private: no # should this be visible or hidden like a password
     
  # TASKS ------------------------------------------------------------------------------------
  tasks:

  # PRE-FLIGHT CHECKS ------------------------------------------------------------------------
  - name: Pre-flight check, fail if OS is not Ubuntu.
    when: ansible_distribution != "Ubuntu" and ansible_distribution != "RedHat"
    fail:
      msg: "This script is designed for Ubuntu"

  ############### UBUNTU SETUP SECTION ###############
# ==============================================================================
# PLAY 1: UPGRADE CONTROL PLANE (UBUNTU)
# ==============================================================================
- name: Upgrade Kubernetes Control Plane
  hosts: k8s_masters
  become: yes
  serial: 1 # Strictly upgrade one control plane node at a time
  tasks:
    - name: Cordon the control plane node
      when: ansible_distribution == "Ubuntu"
      command: kubectl cordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"

    - name: Drain the control plane node
      when: ansible_distribution == "Ubuntu"
      command: >
        kubectl drain {{ inventory_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      ignore_errors: yes

    - name: Update Kubernetes APT repository for the new minor version
      when: ansible_distribution == "Ubuntu"
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"

    - name: Update APT cache
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    - name: Unhold kubeadm package
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: kubeadm
        selection: install

    - name: Upgrade kubeadm package (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: "kubeadm={{ k8s_version }}-*"
        state: present
        allow_downgrade: yes

    - name: Hold kubeadm package
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Upload custom configuration (First Master ONLY)
      when: ansible_distribution == "Ubuntu"
      command: kubeadm init phase upload-config kubeadm --config /etc/kubernetes/kubeadm-config-upgrade.yaml
      when: inventory_hostname == groups['k8s_masters'][0]

    - name: Apply kubeadm upgrade (First Master ONLY)
      when: ansible_distribution == "Ubuntu"
      command: kubeadm upgrade apply v{{ k8s_version }} -y
      when: inventory_hostname == groups['k8s_masters'][0]

    - name: Upgrade secondary control plane nodes (Other Masters)
      when: ansible_distribution == "Ubuntu"
      command: kubeadm upgrade node
      when: inventory_hostname != groups['k8s_masters'][0]

    - name: Unhold kubelet and kubectl packages
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: "{{ item }}"
        selection: install
      loop:
        - kubelet
        - kubectl

    - name: Upgrade kubelet and kubectl packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: 
          - "kubelet={{ k8s_version }}-*"
          - "kubectl={{ k8s_version }}-*"
        state: present
        allow_downgrade: yes

    - name: Hold kubelet and kubectl packages
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubectl

    - name: Reload systemd daemon and restart kubelet
      when: ansible_distribution == "Ubuntu"
      systemd:
        daemon_reload: yes
        name: kubelet
        state: restarted

    - name: Uncordon the control plane node (With Wait Logic)
      when: ansible_distribution == "Ubuntu"
      command: kubectl uncordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      retries: 12
      delay: 5

    - name: Restart coredns to prevent dns resolving problem
      command: kubectl rollout restart deploy -n kube-system -l k8s-app=kube-dns --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      delay: 10
      retries: 3

    - name: Restart azure workload webhook deployment to prevent keyvault problem
      command: kubectl rollout restart deploy -n azure-workload-identity-system --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      delay: 10
      retries: 3

# ==============================================================================
# PLAY 2: UPGRADE WORKER NODES (UBUNTU)
# ==============================================================================
    - name: Cordon the worker node
      when: ansible_distribution == "Ubuntu"
      command: kubectl cordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"

    - name: Drain the worker node
      when: ansible_distribution == "Ubuntu"
      command: >
        kubectl drain {{ inventory_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --force
        --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"

    - name: Update Kubernetes APT repository for the new minor version
      when: ansible_distribution == "Ubuntu"
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"

    - name: Update APT cache
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    - name: Unhold kubeadm package
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: kubeadm
        selection: install

    - name: Upgrade kubeadm package (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: "kubeadm={{ k8s_version }}-*"
        state: present
        allow_downgrade: yes

    - name: Hold kubeadm package
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Upgrade local node configuration
      when: ansible_distribution == "Ubuntu"
      command: kubeadm upgrade node

    - name: Unhold kubelet package
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: kubelet
        selection: install

    - name: Upgrade kubelet package (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: "kubelet={{ k8s_version }}-*"
        state: present
        allow_downgrade: yes

    - name: Hold kubelet package
      when: ansible_distribution == "Ubuntu"
      dpkg_selections:
        name: kubelet
        selection: hold

    - name: Reload systemd daemon and restart kubelet
      when: ansible_distribution == "Ubuntu"
      systemd:
        daemon_reload: yes
        name: kubelet
        state: restarted

    - name: Uncordon the worker node (With Wait Logic)
      when: ansible_distribution == "Ubuntu"
      command: kubectl uncordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      retries: 12
      delay: 5


############### RedHat SETUP SECTION ###############
# ==============================================================================
# PLAY 1: UPGRADE CONTROL PLANE
# ==============================================================================
- name: Upgrade Kubernetes Control Plane
  hosts: k8s_masters
  become: yes
  serial: 1 # Strictly upgrade one control plane node at a time
  tasks:
    - name: Cordon the control plane node
      command: kubectl cordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      delay: 30
      retries: 3

    - name: Drain the control plane node
      command: >
        kubectl drain {{ inventory_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      ignore_errors: yes

    - name: Add kubernetes repository
      when: ansible_distribution == "RedHat"
      shell: | 
        cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://pkgs.k8s.io/core:/stable:/{{ k8s_apt_pkg_version }}/rpm/
        enabled=1
        gpgcheck=1
        gpgkey=https://pkgs.k8s.io/core:/stable:/{{ k8s_apt_pkg_version }}/rpm/repodata/repomd.xml.key
        exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
        EOF

    - name: Upgrade kubeadm package (RHEL)
      dnf:
        name: "kubeadm-{{ k8s_version }}"
        state: present
        disable_excludes: kubernetes

    - name: Verify kubeadm version
      command: kubeadm version
      register: kubeadm_ver
    - debug: msg="{{ kubeadm_ver.stdout }}" 

    - name: Upload custom configuration to the cluster # upgrade with existing kubeadm config (need to get and edit manually)
      command: kubeadm init phase upload-config kubeadm --config /etc/kubernetes/kubeadm-config-upgrade.yaml
      when: inventory_hostname == groups['control_plane'][0]

    - name: Apply kubeadm upgrade plan
      command: kubeadm upgrade plan v{{ k8s_version }}
      register: upgrade_plan
      when: inventory_hostname == groups['k8s_masters'][0] # Only needed on the first master

    - name: Apply kubeadm upgrade
      command: kubeadm upgrade apply v{{ k8s_version }} -y
      when: inventory_hostname == groups['k8s_masters'][0]

    - name: Upgrade secondary control plane nodes
      command: kubeadm upgrade node
      when: inventory_hostname != groups['k8s_masters'][0]

    - name: Upgrade kubelet and kubectl packages (RHEL)
      dnf:
        name: 
          - "kubelet-{{ k8s_version }}"
          - "kubectl-{{ k8s_version }}"
        state: present
        disable_excludes: kubernetes

    - name: Reload systemd daemon and restart kubelet
      systemd:
        daemon_reload: yes
        name: kubelet
        state: restarted

    - name: Uncordon the control plane node
      command: kubectl uncordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      delay: 10
      retries: 3

    - name: Restart coredns to prevent dns resolving problem
      command: kubectl rollout restart deploy -n kube-system -l k8s-app=kube-dns --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      delay: 10
      retries: 3

    - name: Restart azure workload webhook deployment to prevent keyvault problem
      command: kubectl rollout restart deploy -n azure-workload-identity-system --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      delay: 10
      retries: 3

# ==============================================================================
# PLAY 2: UPGRADE WORKER NODES
# ==============================================================================
- name: Upgrade Kubernetes Worker Nodes
  hosts: worker_nodes
  become: yes
  serial: 1 # Strictly upgrade one worker at a time
  tasks:

    - name: Cordon the worker node
      command: kubectl cordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      delay: 30
      retries: 3

    - name: Drain the worker node
      command: >
        kubectl drain {{ inventory_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --kubeconfig=/etc/kubernetes/admin.conf --force
      delegate_to: "{{ groups['k8s_masters'][0] }}"

    - name: Add kubernetes repository
      when: ansible_distribution == "RedHat"
      shell: | 
        cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://pkgs.k8s.io/core:/stable:/{{ k8s_apt_pkg_version }}/rpm/
        enabled=1
        gpgcheck=1
        gpgkey=https://pkgs.k8s.io/core:/stable:/{{ k8s_apt_pkg_version }}/rpm/repodata/repomd.xml.key
        exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
        EOF

    - name: Upgrade kubeadm package (RHEL)
      dnf:
        name: "kubeadm-{{ k8s_version }}"
        state: present
        disable_excludes: kubernetes

    - name: Upgrade local node configuration
      command: kubeadm upgrade node

    - name: Upgrade kubelet package (RHEL)
      dnf:
        name: "kubelet-{{ k8s_version }}"
        state: present
        disable_excludes: kubernetes

    - name: Reload systemd daemon and restart kubelet
      systemd:
        daemon_reload: yes
        name: kubelet
        state: restarted

    - name: Uncordon the worker node
      command: kubectl uncordon {{ inventory_hostname }} --kubeconfig=/etc/kubernetes/admin.conf
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      register: uncordon_result
      until: uncordon_result.rc == 0
      delay: 10
      retries: 3